<?php

namespace App\Services\v1\Group;

use App\Models\Group;
use App\Repositories\GroupRepository;
use App\Services\Contracts\BaseService;
use App\Services\Contracts\Makable;
use Illuminate\Database\Eloquent\Model;

/**
 * @extends BaseService<Group>
 * @property GroupRepository $repository
 */
class GroupService extends BaseService
{
    use Makable;

    protected string $repositoryClass = GroupRepository::class;

    public function store(array $data, array $relationships = []): Model
    {
        /** @var Group $group */
        $group = parent::store($data, $relationships); // TODO: Change the autogenerated stub

        if (isset($data['users'])) {
            $group->users()->sync($data['users']);
        }

        return $group;
    }

    public function update(array $data, $id, array $relationships = []): ?Model
    {
        /** @var Group|null $group */
        $group = parent::update($data, $id, $relationships); // TODO: Change the autogenerated stub

        if (isset($data['users'])) {
            $group?->users()?->sync($data['users']);
        }

        return $group;
    }
}
