/* This file is generated by Ziggy. */
declare module "ziggy-js" {
    interface RouteList {
        "cubeta.starter.settings": [];
        "cubeta.starter.settings.set": [];
        "cubeta.starter.add.actor": [];
        "cubeta.starter.clear.logs": [];
        "cubeta.starter.generate.page": [];
        "cubeta.starter.generate": [];
        "v1.web.public.login": [];
        "v1.web.public.request.reset.password.code": [];
        "v1.web.public.validate.reset.password.code": [];
        "v1.web.public.change.password": [];
        "v1.web.public.register": [];
        "v1.web.protected.update.user.data": [];
        "v1.web.protected.user.details": [];
        "v1.web.protected.logout": [];
        "storage.local": [
            {
                name: "path";
                required: true;
            },
        ];
    }
}
export {};
